const LANG = {
  zh: {
    name: '爪爪',
    tooltip: '爪爪 — Claude Code Companion',
    tray: {
      coffee: '☕ 給爪爪咖啡',
      clap: '👏 拍拍手',
      sunglasses: '😎 戴墨鏡',
      headphones: '🎧 聽音樂',
      typing: '⌨ 打字',
      quit: '❌ 離開',
    },
    speech: {
      startup: '開工了！',
      typing: ['寫程式中～', '讓我想想...', '嗯嗯...', '認真工作中！', '這段有點難...', '快好了快好了', '集中精神！', '加油加油～', '寫到一半了', '思考中...'],
      clapping: ['完成了！', '太棒了！', '做得好～', '又解決一個了！'],
      sunglasses: ['全部搞定😎', '收工！', '完美～'],
      latte: ['謝謝咖啡☕', '好好喝～', '有咖啡就有力氣！'],
      headphones: ['🎵～', '等你回來～', '聽歌中', '休息一下～'],
      google_service: ['查 Google 資料～', '翻翻抽屜...', '找到了！'],
      dizzy: ['休息一下吧～', '工作50分鐘了！', '眼睛好花...', '站起來動一動～', '該休息囉！'],
      rest: ['爪爪不在座位上', '桌上好安靜...', '去哪了呢？', '椅子還是溫的'],
      restInterrupted: ['不是說要休息嗎～', '才剛坐下欸...', '好吧好吧...', '人類你不累嗎？', '嗚…回來了啦'],
      poke: ['幹嘛啦～', '別戳我！', '在工作欸！', '嗚…', '好癢！', '再戳就咬你喔', '？', '做什麼啦～'],
    },
    restTag: (mins) => '爪爪去休息' + mins + '分鐘',
    restTagInit: '爪爪去休息10分鐘',
    restTagBack: '爪爪回來了！',
  },
  en: {
    name: 'Clawd',
    tooltip: 'Clawd — Claude Code Companion',
    tray: {
      coffee: '☕ Coffee',
      clap: '👏 Clap',
      sunglasses: '😎 Sunglasses',
      headphones: '🎧 Music',
      typing: '⌨ Typing',
      quit: '❌ Quit',
    },
    speech: {
      startup: "Let's go!",
      typing: ['Coding~', 'Hmm let me think...', 'Mm-hm...', 'Working hard!', 'This part is tricky...', 'Almost done!', 'Focus!', "C'mon c'mon~", 'Halfway there', 'Thinking...'],
      clapping: ['Done!', 'Awesome!', 'Nice work~', 'Another one solved!'],
      sunglasses: ['All done 😎', "That's a wrap!", 'Perfect~'],
      latte: ['Thanks for the coffee ☕', 'So good~', 'Coffee = power!'],
      headphones: ['🎵~', 'Waiting for you~', 'Listening to music', 'Taking a break~'],
      google_service: ['Checking Google~', 'Rummaging the drawer...', 'Found it!'],
      dizzy: ["Let's take a break~", '50 minutes already!', 'Eyes going blurry...', 'Stand up and stretch~', 'Break time!'],
      rest: ['Clawd is away', "It's quiet here...", 'Where did they go?', 'The chair is still warm'],
      restInterrupted: ["Weren't we resting~?", 'Just sat down...', 'Fine fine...', "Aren't you tired?", "Ugh... I'm back"],
      poke: ['Hey~', "Don't poke me!", "I'm working!", 'Ow...', 'That tickles!', "Poke again and I'll bite", '?', 'What~'],
    },
    restTag: (mins) => 'Clawd resting ' + mins + ' min',
    restTagInit: 'Clawd resting 10 min',
    restTagBack: 'Clawd is back!',
  },
  ja: {
    name: 'Clawd',
    tooltip: 'Clawd — Claude Code Companion',
    tray: {
      coffee: '☕ コーヒー',
      clap: '👏 拍手',
      sunglasses: '😎 サングラス',
      headphones: '🎧 音楽',
      typing: '⌨ タイピング',
      quit: '❌ 終了',
    },
    speech: {
      startup: '仕事開始！',
      typing: ['コード書いてる～', 'うーん…', 'ふむふむ…', '真剣に作業中！', 'ここ難しい…', 'もうすぐ！', '集中！', 'がんばるぞ～', '半分できた', '考え中…'],
      clapping: ['できた！', 'すごい！', 'よくできた～', 'また一つ解決！'],
      sunglasses: ['全部完了😎', 'おつかれ！', '完璧～'],
      latte: ['コーヒーありがとう☕', 'おいしい～', 'コーヒーは元気の源！'],
      headphones: ['🎵～', '待ってるよ～', '音楽聴いてる', 'ちょっと休憩～'],
      google_service: ['Google調べ中～', '引き出しガサガサ…', '見つけた！'],
      dizzy: ['休憩しよう～', 'もう50分だよ！', '目がぐるぐる…', '立って伸びして～', '休憩の時間！'],
      rest: ['Clawdは席を外し中', '静かな机…', 'どこ行ったかな？', '椅子まだあったかい'],
      restInterrupted: ['休憩じゃなかったの～？', '座ったばかりなのに…', 'しょうがないな…', '人間、疲れないの？', 'うぅ…戻ったよ'],
      poke: ['なに～', 'つつかないで！', '仕事中だよ！', 'うぅ…', 'くすぐったい！', 'もう一回つついたら噛むよ', '？', 'なにするの～'],
    },
    restTag: (mins) => 'Clawd 休憩中 ' + mins + '分',
    restTagInit: 'Clawd 休憩中 10分',
    restTagBack: 'Clawd 戻ったよ！',
  }
};

module.exports = LANG;
